### ISSUE TITLE
Unable to setupDecompWorkspace

### ISSUE THREAD

**Issue by SamLam140330** [SinTh0r4s/ExampleMod1.7.10#65]
Do you know how to solve it? I am trying to make a 1.7.10 mod today but seems there are some problems after clicking the setupDecompWorkspace button

The server returned HTTP response code: 403 for URL: https://s3.amazonaws.com/Minecraft.Download/versions/1.7.10/1.7.10.jar

**Comment by C0bra5** [comment]
this repo fixes this issue: https://github.com/GTNewHorizons/ExampleMod1.7.10

**Comment by ChrisJStone** [comment]
updating the build script seams to resolve the issue

**Comment by Derailedzack** [comment]
This now happens for the asset index for 1.7.10
